services:
  database:
    image: postgres:16-alpine
    container_name: io-podmanager-db
    env_file:
      - .env
    volumes:
      - type: volume
        source: postgres
        target: "/var/lib/postgresql/data"
        volume:
          nocopy: true
    ports:
      - "5432:5432"
    restart: unless-stopped

  queue-broker:
    image: redis:latest
    container_name: io-podmanager-queue-broker
    volumes:
      - queue_broker_data:/data
    ports:
      - '6379:6379'
    restart: unless-stopped

  queue_backend:
    image: redis:latest
    container_name: io-podmanager-queue-backend
    volumes:
      - queue_backend_data:/data
    ports:
      - '6380:6379'
    restart: unless-stopped

volumes:
  postgres:
  queue_broker_data:
  queue_backend_data: